# Generated by Django 4.2.7 on 2026-03-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_commission_created_at_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commission',
            name='admin_commission_created_desc',
        ),
        migrations.RenameIndex(
            model_name='commission',
            new_name='admin_commi_status_2df1b1_idx',
            old_name='admin_commi_status_3b2fb2_idx',
        ),
        migrations.RenameIndex(
            model_name='commission',
            new_name='admin_commi_branch__369eaf_idx',
            old_name='admin_commi_branch__8af8c8_idx',
        ),
        migrations.RenameIndex(
            model_name='commission',
            new_name='admin_commi_staff_i_6ad28e_idx',
            old_name='admin_commi_staff_i_ec8fda_idx',
        ),
        migrations.RenameIndex(
            model_name='commission',
            new_name='admin_commi_custome_80d2ce_idx',
            old_name='admin_commi_custome_9071d1_idx',
        ),
    ]
