# Generated by Django 4.2.7 on 2026-03-23 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admin_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("couple_name_1", models.CharField(max_length=150)),
                ("couple_name_2", models.CharField(max_length=150)),
                ("wedding_date", models.DateField()),
                ("location", models.CharField(max_length=200)),
                ("story_text", models.TextField()),
                ("couple_photo", models.ImageField(blank=True, null=True, upload_to="success_stories/")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published")], default="draft", max_length=20)),
                ("is_featured", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_success_stories",
                        to="admin_auth.adminuser",
                    ),
                ),
            ],
            options={
                "db_table": "admin_success_story",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["status"], name="admin_succe_status_f7beea_idx"),
                    models.Index(fields=["is_featured"], name="admin_succe_is_feat_4a2ba5_idx"),
                    models.Index(fields=["created_at"], name="admin_succe_created_4ac8aa_idx"),
                ],
            },
        ),
    ]
