# Generated by Django 4.2.7 on 2026-03-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='successstory',
            new_name='admin_succe_status_39d174_idx',
            old_name='admin_succe_status_f7beea_idx',
        ),
        migrations.RenameIndex(
            model_name='successstory',
            new_name='admin_succe_is_feat_f84de3_idx',
            old_name='admin_succe_is_feat_4a2ba5_idx',
        ),
        migrations.RenameIndex(
            model_name='successstory',
            new_name='admin_succe_created_5e2eb6_idx',
            old_name='admin_succe_created_4ac8aa_idx',
        ),
    ]
