# Generated by Django 4.2.29 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_userreligion_caste_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="family_completed",
            field=models.BooleanField(default=False),
        ),
    ]

