# Generated by Django 4.2.7 on 2026-03-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userfamily_and_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreligion',
            name='partner_caste_preference',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('own_caste_only', 'Own caste only')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='userreligion',
            name='partner_preference_type',
            field=models.CharField(blank=True, choices=[('own_religion_only', 'Own religion only'), ('open_to_all', 'Open to all religions'), ('specific_religions', 'Specific religions')], default='open_to_all', max_length=30),
        ),
        migrations.AddField(
            model_name='userreligion',
            name='partner_religion_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
