# Generated by Django 4.2.7 on 2026-03-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userphotos_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonal',
            name='children_count',
            field=models.PositiveSmallIntegerField(db_column='children_count', default=0),
        ),
        migrations.RenameField(
            model_name='userpersonal',
            old_name='children_count',
            new_name='number_of_children',
        ),
    ]
