# Generated by Django 4.2.29 on 2026-03-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_alter_userpersonal_children_count_and_more"),
        ("profiles", "0004_userprofile_family_completed"),
    ]

    operations = []

