# Generated by Django 4.2.7 on 2026-03-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_userprofile_admin_verified_horoscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='working_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userfamily',
            name='family_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userfamily',
            name='family_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userpersonal',
            name='children_living_with',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userphotos',
            name='profile_photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='horoscope_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userreligion',
            name='gothram',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
