# Generated by Django 4.2.7 on 2026-04-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_replace_partner_caste_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfamily',
            name='father_status',
            field=models.CharField(blank=True, choices=[('Alive', 'Alive'), ('Late', 'Late')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userfamily',
            name='mother_status',
            field=models.CharField(blank=True, choices=[('Alive', 'Alive'), ('Late', 'Late')], default='', max_length=20),
        ),
    ]
