# Generated by Django 5.2.13 on 2026-05-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_userreligion_partner_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
