# Generated by Django 4.2.30 on 2026-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_userpersonal_reason_for_divorce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='admin_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Platform verification (admin). Distinct from mobile_verified.'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['admin_verified', 'has_horoscope'], name='prof_up_verif_horo_idx'),
        ),
    ]
