# Generated by Django 4.2.7 on 2026-03-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='admin_audit_created_d091be_idx',
            old_name='admin_audit__created_71467f_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='admin_audit_action_9d8c52_idx',
            old_name='admin_audit_action_612bc2_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='admin_audit_actor_r_9ec3cb_idx',
            old_name='admin_audit_actor_r_6f21cc_idx',
        ),
    ]
