# Generated by Django 4.2.7 on 2026-03-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0002_auditlog_role'),
        ('audit_log', '0002_rename_admin_audit__created_71467f_idx_admin_audit_created_d091be_idx_and_more'),
    ]

    operations = [
    ]
