# Generated by Django 4.2.7 on 2026-03-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0003_merge_20260326_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('payment_create', 'Payment Create'), ('otp_verify', 'OTP Verify'), ('profile_update', 'Profile Update'), ('profile_verify', 'Profile Verified'), ('profile_unverify', 'Profile Unverified'), ('commission_create', 'Commission Created'), ('commission_update', 'Commission Updated'), ('branch_update', 'Branch Updated'), ('staff_update', 'Staff Updated'), ('subscription_update', 'Subscription Updated'), ('other', 'Other')], max_length=50),
        ),
    ]
