# Generated by GPT-5.2 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_log", "0005_auditlog_enriched_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditlog",
            old_name="target_user_name",
            new_name="target_profile_name",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="endpoint",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                blank=True,
                choices=[("create_profile", "Create Profile"), ("update_profile", "Update Profile")],
                max_length=20,
            ),
        ),
    ]

