map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    server_name api.aiswaryamatrimonials.com;

    location /media/ {
        alias /opt/aiswaryamatrimonials/Matrimony_Backend/media/;
        access_log off;
        expires 7d;
        add_header Cache-Control "public";
    }

    location /ws/ {
        proxy_pass http://172.28.0.12:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_connect_timeout 5s;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_buffering off;
        proxy_redirect off;
    }

    location / {
        proxy_pass http://172.28.0.12:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
    }

    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/api.aiswaryamatrimonials.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.aiswaryamatrimonials.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = api.aiswaryamatrimonials.com) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name api.aiswaryamatrimonials.com;
    return 404;
}
