# Generated by Django 4.2.7 on 2026-03-26 03:05
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0002_astrology_pdf_credit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='astrologypdfcredit',
            new_name='astrology_p_user_id_292032_idx',
            old_name='astrology_pd_user_id_2b8fbd_idx',
        ),
    ]
