# Generated by Django 5.2.13 on 2026-04-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0003_rename_astrology_pd_user_id_2b8fbd_idx_astrology_p_user_id_292032_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='janana_shishtam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horoscope',
            name='navamsa_chart',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='horoscope',
            name='shishta_dasa',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
