# Generated by Django 5.2.13 on 2026-04-20 04:47

import astrology.models
from django.db import migrations, models


def _backfill_empty_horoscope_json(apps, schema_editor):
    Horoscope = apps.get_model('astrology', 'Horoscope')
    Horoscope.objects.filter(navamsa_chart__isnull=True).update(navamsa_chart={})
    Horoscope.objects.filter(shishta_dasa__isnull=True).update(shishta_dasa={})


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0004_horoscope_navamsa_shishta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='navamsa_chart',
            field=models.JSONField(blank=True, default=astrology.models._horoscope_json_default, null=True),
        ),
        migrations.AlterField(
            model_name='horoscope',
            name='shishta_dasa',
            field=models.JSONField(blank=True, default=astrology.models._horoscope_json_default, null=True),
        ),
        migrations.RunPython(_backfill_empty_horoscope_json, migrations.RunPython.noop),
    ]
