# Generated by Django 5.2.13 on 2026-04-21 03:02

import astrology.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0005_horoscope_json_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='navamsa_chart',
            field=models.JSONField(blank=True, default=astrology.models._horoscope_json_default, null=True),
        ),
        migrations.AlterField(
            model_name='horoscope',
            name='shishta_dasa',
            field=models.JSONField(blank=True, default=astrology.models._horoscope_json_default, null=True),
        ),
    ]
