# Generated by Django 5.2.13 on 2026-05-14 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0006_alter_horoscope_navamsa_chart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoroscopeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pr_name', models.CharField(blank=True, max_length=255)),
                ('pr_dob', models.DateField(blank=True, null=True)),
                ('pr_tob', models.TimeField(blank=True, null=True)),
                ('pr_lat', models.FloatField(blank=True, null=True)),
                ('pr_lon', models.FloatField(blank=True, null=True)),
                ('pr_tz', models.FloatField(default=5.5)),
                ('pr_rasi', models.CharField(blank=True, help_text='11-char string A-L: each position = planet zodiac sign', max_length=11)),
                ('pr_amsa', models.CharField(blank=True, max_length=11)),
                ('pr_bhav', models.CharField(blank=True, max_length=11)),
                ('pr_star', models.IntegerField(blank=True, help_text='Nakshatra number 1-27', null=True)),
                ('pr_pada', models.PositiveSmallIntegerField(blank=True, help_text='Nakshatra padam 1-4', null=True)),
                ('pr_dasabalance', models.IntegerField(blank=True, help_text='Sishta dasa balance in days', null=True)),
                ('lagnam', models.CharField(blank=True, max_length=50)),
                ('rasi_sign', models.CharField(blank=True, max_length=50)),
                ('star_name', models.CharField(blank=True, max_length=50)),
                ('nakshatra_pada', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gana', models.CharField(blank=True, max_length=20)),
                ('yoni', models.CharField(blank=True, max_length=20)),
                ('rajju', models.CharField(blank=True, max_length=20)),
                ('is_calculated', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horoscope_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'horoscope_profile',
            },
        ),
        migrations.CreateModel(
            name='PoruthamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinam', models.IntegerField(choices=[(1, 'Uthamam'), (2, 'Madhyamam'), (3, 'Adhamam'), (4, 'Neecham')], null=True)),
                ('ganam', models.IntegerField(choices=[(1, 'Uthamam'), (2, 'Madhyamam'), (3, 'Adhamam'), (4, 'Neecham')], null=True)),
                ('mahendra', models.IntegerField(choices=[(1, 'Uthamam'), (2, 'Madhyamam'), (3, 'Adhamam'), (4, 'Neecham')], null=True)),
                ('sthree_deerga', models.IntegerField(choices=[(1, 'Uthamam'), (2, 'Madhyamam'), (3, 'Adhamam'), (4, 'Neecham')], null=True)),
                ('yoni', models.IntegerField(choices=[(1, 'Uthamam'), (2, 'Madhyamam'), (3, 'Adhamam'), (4, 'Neecham')], null=True)),
                ('rasi', models.IntegerField(choices=[(1, 'Uthamam'), (2, 'Madhyamam'), (3, 'Adhamam'), (4, 'Neecham')], null=True)),
                ('rasyadhipam', models.IntegerField(choices=[(1, 'Uthamam'), (2, 'Madhyamam'), (3, 'Adhamam'), (4, 'Neecham')], null=True)),
                ('vasyam', models.IntegerField(choices=[(1, 'Uthamam'), (2, 'Madhyamam'), (3, 'Adhamam'), (4, 'Neecham')], null=True)),
                ('rajju_dosham', models.IntegerField(choices=[(1, 'Uthamam'), (2, 'Madhyamam'), (3, 'Adhamam'), (4, 'Neecham')], null=True)),
                ('vedha_dosham', models.IntegerField(choices=[(1, 'Uthamam'), (2, 'Madhyamam'), (3, 'Adhamam'), (4, 'Neecham')], null=True)),
                ('chovva_dosham', models.BooleanField(null=True)),
                ('dasa_sandhi', models.BooleanField(null=True)),
                ('bride_papatha', models.FloatField(null=True)),
                ('groom_papatha', models.FloatField(null=True)),
                ('total_porutham_count', models.IntegerField(default=0)),
                ('uthamam_count', models.IntegerField(default=0)),
                ('madhyamam_count', models.IntegerField(default=0)),
                ('adhamam_count', models.IntegerField(default=0)),
                ('has_dosha', models.BooleanField(default=False)),
                ('overall_result', models.CharField(blank=True, max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porutham_as_bride', to=settings.AUTH_USER_MODEL)),
                ('groom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porutham_as_groom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'porutham_result',
                'unique_together': {('bride', 'groom')},
            },
        ),
        migrations.DeleteModel(
            name='Horoscope',
        ),
    ]
