# Generated by Django 4.2.30 on 2026-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0007_replace_horoscope_with_exe_bridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscopeprofile',
            name='is_calculated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='horoscopeprofile',
            index=models.Index(fields=['is_calculated', 'pr_star'], name='horoscope_calc_star_idx'),
        ),
        migrations.AddIndex(
            model_name='horoscopeprofile',
            index=models.Index(fields=['pr_star'], name='horoscope_pr_star_idx'),
        ),
    ]
