# Generated by Django 4.2.7 on 2026-03-13 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('profile_view_limit', models.PositiveIntegerField(default=0, help_text='Number of full profile views allowed; 0 = unlimited')),
                ('interest_limit', models.PositiveIntegerField(default=0, help_text='Number of interests allowed to send; 0 = unlimited')),
                ('chat_limit', models.PositiveIntegerField(default=0, help_text='Number of chat initiations; 0 = unlimited')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Plan validity in days')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plans_plan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_views_used', models.PositiveIntegerField(default=0)),
                ('interests_used', models.PositiveIntegerField(default=0)),
                ('chat_used', models.PositiveIntegerField(default=0)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_plans', to='plans.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User plan',
                'verbose_name_plural': 'User plans',
                'db_table': 'plans_user_plan',
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('viewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plans_profile_view',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['viewer', 'viewed_user'], name='plans_profi_viewer__b69bb8_idx'), models.Index(fields=['viewer', 'timestamp'], name='plans_profi_viewer__36fd6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plans_interest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'receiver'], name='plans_inter_sender__603e50_idx')],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
