# Generated by Django 4.2.7 on 2026-03-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total service charge at purchase (by gender)', max_digits=12),
        ),
    ]
