# Generated by Django 4.2.29 on 2026-03-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_interest_status_alter_userplan_service_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('plan_purchase', 'Plan Purchase'), ('profile_boost', 'Profile Boost'), ('refund', 'Refund')], default='plan_purchase', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='plans.plan'),
        ),
    ]
