# Generated by Django 4.2.29 on 2026-03-18

from django.db import migrations, models


def dedupe_profile_views(apps, schema_editor):
    """
    Remove duplicate ProfileView rows before adding unique constraint on
    (viewer, viewed_user). Keeps the earliest row per pair (by smallest id).
    """
    ProfileView = apps.get_model("plans", "ProfileView")

    # Use raw SQL for speed and minimal memory. This keeps the lowest id per pair.
    table = ProfileView._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == "sqlite":
            cursor.execute(
                f"""
                DELETE FROM {table}
                WHERE id NOT IN (
                    SELECT MIN(id)
                    FROM {table}
                    GROUP BY viewer_id, viewed_user_id
                )
                """
            )
        else:
            cursor.execute(
                f"""
                DELETE FROM {table} pv
                USING {table} pv2
                WHERE pv.viewer_id = pv2.viewer_id
                  AND pv.viewed_user_id = pv2.viewed_user_id
                  AND pv.id > pv2.id
                """
            )


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0008_transaction_type_plan_nullable"),
    ]

    operations = [
        migrations.RunPython(dedupe_profile_views, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="profileview",
            constraint=models.UniqueConstraint(
                fields=("viewer", "viewed_user"),
                name="uniq_profile_view_pair",
            ),
        ),
    ]

