# Generated by Django 4.2.29 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0009_unique_profile_view_pair"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplan",
            name="profile_view_bonus",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userplan",
            name="interest_bonus",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userplan",
            name="chat_bonus",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userplan",
            name="horoscope_bonus",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userplan",
            name="contact_view_bonus",
            field=models.PositiveIntegerField(default=0),
        ),
    ]

