# Generated by Django 4.2.29 on 2026-03-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0010_fix_service_charge_amounts"),
        ("plans", "0010_userplan_bonus_fields"),
    ]

    operations = []

