# Generated by Django 4.2.7 on 2026-03-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_transaction_type_created_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='plans_txn_type_created_desc',
        ),
    ]
