# Generated by Django 4.2.7 on 2026-03-25 11:26
# Index is removed in 0014_remove_transaction_plans_txn_type_created_desc; this
# migration follows 0015_merge so the graph has a single leaf.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_merge_20260325_1548'),
    ]

    operations = []
