# Generated by Django 4.2.7 on 2026-03-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_transaction_astrology_pdf_types'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='plans_txn_type_created_desc',
        ),
    ]
