# Generated by Django 4.2.7 on 2026-04-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0016_profileview_userprofile_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileview',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='profileview',
            new_name='plans_profi_viewer__9553d3_idx',
            old_name='plans_profi_viewer_pr_f6a1_idx',
        ),
    ]
