# Generated by Django 4.2.7 on 2026-04-27 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0018_profileview_last_viewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileview',
            name='last_viewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Updated on every profile view; used for home-slider ordering among already-viewed profiles.'),
        ),
    ]
