# Generated by Django 4.2.30 on 2026-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0020_profileview_unlocked'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='chat_msg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'read_at', 'sender'], name='chat_msg_conv_read_sender_idx'),
        ),
    ]
