# Generated by Django 5.2.16 on 2026-09-04 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0022_plan_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('receipt', models.CharField(blank=True, max_length=64)),
                ('amount_paise', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('purpose', models.CharField(blank=True, db_index=True, max_length=40)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('skipped', 'Skipped')], db_index=True, default='created', max_length=20)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='razorpay_orders', to='plans.plan')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='razorpay_orders', to='plans.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='razorpay_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Razorpay order',
                'verbose_name_plural': 'Razorpay orders',
                'db_table': 'plans_razorpay_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RazorpayWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(blank=True, db_index=True, max_length=64)),
                ('signature_valid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('invalid_signature', 'Invalid signature'), ('not_configured', 'Not configured'), ('malformed', 'Malformed'), ('ignored', 'Ignored'), ('fulfilled', 'Fulfilled'), ('duplicate', 'Duplicate'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='failed', max_length=32)),
                ('http_status', models.PositiveSmallIntegerField(default=0)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('response_summary', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='plans.razorpayorder')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='razorpay_webhook_events', to='plans.transaction')),
            ],
            options={
                'verbose_name': 'Razorpay webhook event',
                'verbose_name_plural': 'Razorpay webhook events',
                'db_table': 'plans_razorpay_webhook_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
