# Generated by Django 4.2.7 on 2026-03-23 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('admin_auth', '0001_initial'),
        ('staff_mgmt', '0002_alter_staffprofile_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the payroll month, e.g. 2026-02-01')),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, help_text='Sum of paid commissions in this month', max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_records', to='admin_auth.adminuser')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to='branches.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to='staff_mgmt.staffprofile')),
            ],
            options={
                'db_table': 'admin_salary_record',
                'ordering': ['-month', '-id'],
                'indexes': [models.Index(fields=['month'], name='admin_salar_month_a4c706_idx'), models.Index(fields=['status'], name='admin_salar_status_d3b7e5_idx'), models.Index(fields=['branch'], name='admin_salar_branch__beead3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='salaryrecord',
            constraint=models.UniqueConstraint(fields=('staff', 'month'), name='uniq_salary_staff_month'),
        ),
    ]
