NAKSHATRA_DATA = [
    {'name': 'Ashwini', 'gana': 'Deva', 'yoni': 'Horse', 'nadi': 'Adi', 'rajju': 'Pada', 'rasi': 'Mesha'},
    {'name': 'Bharani', 'gana': 'Manushya', 'yoni': 'Elephant', 'nadi': 'Madhya', 'rajju': 'Kati', 'rasi': 'Mesha'},
    {'name': 'Krittika', 'gana': 'Rakshasa', 'yoni': 'Sheep', 'nadi': 'Antya', 'rajju': 'Nabhi', 'rasi': 'Mesha/Vrishabha'},
    {'name': 'Rohini', 'gana': 'Manushya', 'yoni': 'Serpent', 'nadi': 'Antya', 'rajju': 'Kanta', 'rasi': 'Vrishabha'},
    {'name': 'Mrigashirsha', 'gana': 'Deva', 'yoni': 'Serpent', 'nadi': 'Madhya', 'rajju': 'Sira', 'rasi': 'Vrishabha/Mithuna'},
    {'name': 'Ardra', 'gana': 'Manushya', 'yoni': 'Dog', 'nadi': 'Adi', 'rajju': 'Pada', 'rasi': 'Mithuna'},
    {'name': 'Punarvasu', 'gana': 'Deva', 'yoni': 'Cat', 'nadi': 'Adi', 'rajju': 'Kati', 'rasi': 'Mithuna/Karka'},
    {'name': 'Pushya', 'gana': 'Deva', 'yoni': 'Sheep', 'nadi': 'Madhya', 'rajju': 'Nabhi', 'rasi': 'Karka'},
    {'name': 'Ashlesha', 'gana': 'Rakshasa', 'yoni': 'Cat', 'nadi': 'Antya', 'rajju': 'Kanta', 'rasi': 'Karka'},
    {'name': 'Magha', 'gana': 'Rakshasa', 'yoni': 'Rat', 'nadi': 'Antya', 'rajju': 'Sira', 'rasi': 'Simha'},
    {'name': 'Purva Phalguni', 'gana': 'Manushya', 'yoni': 'Rat', 'nadi': 'Madhya', 'rajju': 'Pada', 'rasi': 'Simha'},
    {'name': 'Uttara Phalguni', 'gana': 'Manushya', 'yoni': 'Cow', 'nadi': 'Adi', 'rajju': 'Kati', 'rasi': 'Simha/Kanya'},
    {'name': 'Hasta', 'gana': 'Deva', 'yoni': 'Buffalo', 'nadi': 'Adi', 'rajju': 'Nabhi', 'rasi': 'Kanya'},
    {'name': 'Chitra', 'gana': 'Rakshasa', 'yoni': 'Tiger', 'nadi': 'Madhya', 'rajju': 'Kanta', 'rasi': 'Kanya/Tula'},
    {'name': 'Swati', 'gana': 'Deva', 'yoni': 'Buffalo', 'nadi': 'Antya', 'rajju': 'Sira', 'rasi': 'Tula'},
    {'name': 'Vishakha', 'gana': 'Rakshasa', 'yoni': 'Tiger', 'nadi': 'Antya', 'rajju': 'Pada', 'rasi': 'Tula/Vrischika'},
    {'name': 'Anuradha', 'gana': 'Deva', 'yoni': 'Deer', 'nadi': 'Madhya', 'rajju': 'Kati', 'rasi': 'Vrischika'},
    {'name': 'Jyeshtha', 'gana': 'Rakshasa', 'yoni': 'Deer', 'nadi': 'Adi', 'rajju': 'Nabhi', 'rasi': 'Vrischika'},
    {'name': 'Mula', 'gana': 'Rakshasa', 'yoni': 'Dog', 'nadi': 'Adi', 'rajju': 'Kanta', 'rasi': 'Dhanus'},
    {'name': 'Purva Ashadha', 'gana': 'Manushya', 'yoni': 'Monkey', 'nadi': 'Madhya', 'rajju': 'Sira', 'rasi': 'Dhanus'},
    {'name': 'Uttara Ashadha', 'gana': 'Manushya', 'yoni': 'Mongoose', 'nadi': 'Antya', 'rajju': 'Pada', 'rasi': 'Dhanus/Makara'},
    {'name': 'Shravana', 'gana': 'Deva', 'yoni': 'Monkey', 'nadi': 'Antya', 'rajju': 'Kati', 'rasi': 'Makara'},
    {'name': 'Dhanishta', 'gana': 'Rakshasa', 'yoni': 'Lion', 'nadi': 'Madhya', 'rajju': 'Nabhi', 'rasi': 'Makara/Kumbha'},
    {'name': 'Shatabhisha', 'gana': 'Rakshasa', 'yoni': 'Horse', 'nadi': 'Adi', 'rajju': 'Kanta', 'rasi': 'Kumbha'},
    {'name': 'Purva Bhadrapada', 'gana': 'Manushya', 'yoni': 'Lion', 'nadi': 'Adi', 'rajju': 'Sira', 'rasi': 'Kumbha/Meena'},
    {'name': 'Uttara Bhadrapada', 'gana': 'Manushya', 'yoni': 'Cow', 'nadi': 'Madhya', 'rajju': 'Pada', 'rasi': 'Meena'},
    {'name': 'Revati', 'gana': 'Deva', 'yoni': 'Elephant', 'nadi': 'Antya', 'rajju': 'Kati', 'rasi': 'Meena'},
]

NAKSHATRA_MAP = {item['name']: item for item in NAKSHATRA_DATA}
