"""Canonical nakṣatra metadata for horoscopes and Dashakoot (single source of truth)."""

NAKSHATRA_DATA = [
    {
        'name': 'Ashwini',
        'gana': 'Deva',
        'yoni': 'Horse',
        'yoni_gender': 'Male',
        'nadi': 'Adi',
        'rajju': 'Pada',
        'rasi': 'Mesha',
    },
    {
        'name': 'Bharani',
        'gana': 'Manushya',
        'yoni': 'Elephant',
        'yoni_gender': 'Male',
        'nadi': 'Madhya',
        'rajju': 'Kati',
        'rasi': 'Mesha',
    },
    {
        'name': 'Krittika',
        'gana': 'Deva',
        'yoni': 'Sheep',
        'yoni_gender': 'Female',
        'nadi': 'Antya',
        'rajju': 'Nabhi',
        'rasi': 'Vrishabha',
    },
    {
        'name': 'Rohini',
        'gana': 'Manushya',
        'yoni': 'Serpent',
        'yoni_gender': 'Female',
        'nadi': 'Antya',
        'rajju': 'Kanta',
        'rasi': 'Vrishabha',
    },
    {
        'name': 'Mrigashirsha',
        'gana': 'Deva',
        'yoni': 'Serpent',
        'yoni_gender': 'Female',
        'nadi': 'Madhya',
        'rajju': 'Sira',
        'rasi': 'Vrishabha/Mithuna',
    },
    {
        'name': 'Ardra',
        'gana': 'Manushya',
        'yoni': 'Dog',
        'yoni_gender': 'Female',
        'nadi': 'Adi',
        'rajju': 'Kanta',
        'rasi': 'Mithuna',
    },
    {
        'name': 'Punarvasu',
        'gana': 'Deva',
        'yoni': 'Cat',
        'yoni_gender': 'Male',
        'nadi': 'Adi',
        'rajju': 'Nabhi',
        'rasi': 'Mithuna/Karka',
    },
    {
        'name': 'Pushya',
        'gana': 'Deva',
        'yoni': 'Sheep',
        'yoni_gender': 'Male',
        'nadi': 'Madhya',
        'rajju': 'Kati',
        'rasi': 'Karka',
    },
    {
        'name': 'Ashlesha',
        'gana': 'Rakshasa',
        'yoni': 'Cat',
        'yoni_gender': 'Female',
        'nadi': 'Antya',
        'rajju': 'Pada',
        'rasi': 'Karka',
    },
    {
        'name': 'Magha',
        'gana': 'Rakshasa',
        'yoni': 'Rat',
        'yoni_gender': 'Male',
        'nadi': 'Antya',
        'rajju': 'Pada',
        'rasi': 'Simha',
    },
    {
        'name': 'Purva Phalguni',
        'gana': 'Manushya',
        'yoni': 'Rat',
        'yoni_gender': 'Female',
        'nadi': 'Madhya',
        'rajju': 'Pada',
        'rasi': 'Simha',
    },
    {
        'name': 'Uttara Phalguni',
        'gana': 'Manushya',
        'yoni': 'Cow',
        'yoni_gender': 'Female',
        'nadi': 'Adi',
        'rajju': 'Nabhi',
        'rasi': 'Simha/Kanya',
    },
    {
        'name': 'Hasta',
        'gana': 'Deva',
        'yoni': 'Buffalo',
        'yoni_gender': 'Female',
        'nadi': 'Adi',
        'rajju': 'Kanta',
        'rasi': 'Kanya',
    },
    {
        'name': 'Chitra',
        'gana': 'Manushya',
        'yoni': 'Tiger',
        'yoni_gender': 'Female',
        'nadi': 'Madhya',
        'rajju': 'Kati',
        'rasi': 'Kanya/Tula',
    },
    {
        'name': 'Swati',
        'gana': 'Deva',
        'yoni': 'Buffalo',
        'yoni_gender': 'Male',
        'nadi': 'Antya',
        'rajju': 'Kanta',
        'rasi': 'Vrischika',
    },
    {
        'name': 'Vishakha',
        'gana': 'Rakshasa',
        'yoni': 'Tiger',
        'yoni_gender': 'Male',
        'nadi': 'Antya',
        'rajju': 'Nabhi',
        'rasi': 'Vrischika/Tula',
    },
    {
        'name': 'Anuradha',
        'gana': 'Deva',
        'yoni': 'Deer',
        'yoni_gender': 'Male',
        'nadi': 'Madhya',
        'rajju': 'Kati',
        'rasi': 'Vrischika',
    },
    {
        'name': 'Jyeshtha',
        'gana': 'Rakshasa',
        'yoni': 'Deer',
        'yoni_gender': 'Female',
        'nadi': 'Adi',
        'rajju': 'Nabhi',
        'rasi': 'Vrischika',
    },
    {
        'name': 'Mula',
        'gana': 'Rakshasa',
        'yoni': 'Dog',
        'yoni_gender': 'Male',
        'nadi': 'Adi',
        'rajju': 'Pada',
        'rasi': 'Dhanus',
    },
    {
        'name': 'Purva Ashadha',
        'gana': 'Manushya',
        'yoni': 'Monkey',
        'yoni_gender': 'Female',
        'nadi': 'Madhya',
        'rajju': 'Kati',
        'rasi': 'Dhanus',
    },
    {
        'name': 'Uttara Ashadha',
        'gana': 'Manushya',
        'yoni': 'Mongoose',
        'yoni_gender': 'Male',
        'nadi': 'Antya',
        'rajju': 'Nabhi',
        'rasi': 'Makara/Dhanus',
    },
    {
        'name': 'Shravana',
        'gana': 'Deva',
        'yoni': 'Monkey',
        'yoni_gender': 'Male',
        'nadi': 'Antya',
        'rajju': 'Kati',
        'rasi': 'Makara',
    },
    {
        'name': 'Dhanishta',
        'gana': 'Manushya',
        'yoni': 'Lion',
        'yoni_gender': 'Female',
        'nadi': 'Madhya',
        'rajju': 'Sira',
        'rasi': 'Makara/Kumbha',
    },
    {
        'name': 'Shatabhisha',
        'gana': 'Rakshasa',
        'yoni': 'Horse',
        'yoni_gender': 'Female',
        'nadi': 'Adi',
        'rajju': 'Kanta',
        'rasi': 'Kumbha',
    },
    {
        'name': 'Purva Bhadrapada',
        'gana': 'Manushya',
        'yoni': 'Lion',
        'yoni_gender': 'Male',
        'nadi': 'Adi',
        'rajju': 'Nabhi',
        'rasi': 'Kumbha/Meena',
    },
    {
        'name': 'Uttara Bhadrapada',
        'gana': 'Manushya',
        'yoni': 'Cow',
        'yoni_gender': 'Female',
        'nadi': 'Madhya',
        'rajju': 'Kati',
        'rasi': 'Meena',
    },
    {
        'name': 'Revati',
        'gana': 'Deva',
        'yoni': 'Elephant',
        'yoni_gender': 'Female',
        'nadi': 'Antya',
        'rajju': 'Pada',
        'rasi': 'Meena',
    },
]

NAKSHATRA_MAP = {item['name']: item for item in NAKSHATRA_DATA}

NAKSHATRA_YONI = {
    row['name']: (row['yoni'], row['yoni_gender']) for row in NAKSHATRA_DATA
}
