"""Roman/English spellings often used on Kerala matrimony UIs (not Malayalam script)."""
NAKSHATRA_UI_LABEL = {
    'Ashwini': 'Aswathi',
    'Bharani': 'Bharani',
    'Krittika': 'Karthika',
    'Rohini': 'Rohini',
    'Mrigashirsha': 'Makayiram',
    'Ardra': 'Thiruvathira',
    'Punarvasu': 'Punartham',
    'Pushya': 'Pooyam',
    'Ashlesha': 'Ayilyam',
    'Magha': 'Makam',
    'Purva Phalguni': 'Pooram',
    'Uttara Phalguni': 'Uthram',
    'Hasta': 'Atham',
    'Chitra': 'Chithira',
    'Swati': 'Chothy',
    'Vishakha': 'Vishakham',
    'Anuradha': 'Anizham',
    'Jyeshtha': 'Thrikketta',
    'Mula': 'Moolam',
    'Purva Ashadha': 'Pooradam',
    'Uttara Ashadha': 'Uthradam',
    'Shravana': 'Thiruvonam',
    'Dhanishta': 'Avittam',
    'Shatabhisha': 'Chathayam',
    'Purva Bhadrapada': 'Pooruruttathi',
    'Uttara Bhadrapada': 'Uthrattathi',
    'Revati': 'Revathi',
}
