# Generated by Django 4.2.7 on 2026-03-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_for',
            field=models.CharField(blank=True, choices=[('myself', 'Myself'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('friend', 'Friend'), ('relative', 'Relative')], help_text='Who the profile is being registered for (e.g. Myself, Son, Daughter)', max_length=20, null=True),
        ),
    ]
