# Generated by Django 4.2.29 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_profile_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tokens_invalid_before",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, reject JWTs issued before this time (e.g. after logout).",
                null=True,
            ),
        ),
    ]

