# Generated by Django 4.2.30 on 2026-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_blocked'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'gender'], name='acc_user_act_gender_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active', '-created_at'], name='acc_user_role_act_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['dob'], name='acc_user_dob_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['branch', 'role'], name='acc_user_branch_role_idx'),
        ),
    ]
