# Generated by Django 4.2.7 on 2026-03-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_seed_education_subject_occupation_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Employment statuses',
                'db_table': 'master_employment_status',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='educationsubject',
            name='educations',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='master.education'),
        ),
    ]
