# Generated by Django 5.2.16 on 2026-08-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_auth', '0002_adminuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_testimonials', to='admin_auth.adminuser')),
            ],
            options={
                'db_table': 'admin_testimonial',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['status'], name='admin_testi_status_86c467_idx'), models.Index(fields=['sort_order'], name='admin_testi_sort_or_2b6f8f_idx'), models.Index(fields=['created_at'], name='admin_testi_created_5685ce_idx')],
            },
        ),
    ]
