from django.urls import path
from .views import (
    ProfileDetailView,
    BasicDetailsView,
    ProfileLocationView,
    ProfileReligionView,
    PartnerPreferencesView,
    ProfilePersonalView,
    ProfileFamilyView,
    ProfileEducationView,
    ProfileGenerateAboutView,
    ProfileAboutView,
    ProfilePhotosView,
    ProfileCompleteView,
    ProfileCompletionView,
    ProfileRegistrationCompletedView,
    ProfileViewsView,
    ProfileBirthDetailsView,
)

urlpatterns = [
    path('', ProfileDetailView.as_view()),
    path('basic/', BasicDetailsView.as_view()),
    path('completion/', ProfileCompletionView.as_view()),
    path('registration-completed/', ProfileRegistrationCompletedView.as_view()),
    path('views/', ProfileViewsView.as_view()),
    path('location/', ProfileLocationView.as_view()),
    path('religion/', ProfileReligionView.as_view()),
    path('partner-preferences/', PartnerPreferencesView.as_view()),
    path('partner-preference/', PartnerPreferencesView.as_view()),
    path('personal/', ProfilePersonalView.as_view()),
    path('family/', ProfileFamilyView.as_view()),
    path('education/', ProfileEducationView.as_view()),
    path('generate-about/', ProfileGenerateAboutView.as_view()),
    path('about/', ProfileAboutView.as_view()),
    path('photos/', ProfilePhotosView.as_view()),
    path('photos/<int:photo_id>/', ProfilePhotosView.as_view()),
    path('birth-details/', ProfileBirthDetailsView.as_view()),
    path('complete/', ProfileCompleteView.as_view()),
]
