# Generated by Django 4.2.7 on 2026-03-23 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0006_seed_education_subject_occupation_income'),
        ('admin_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=10)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('validated', 'Validated'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='validated', max_length=20)),
                ('validation_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_upload_jobs', to='master.branch')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_upload_jobs', to='admin_auth.adminuser')),
            ],
            options={
                'db_table': 'admin_bulk_upload_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='admin_bulk__status_b47778_idx'), models.Index(fields=['created_at'], name='admin_bulk__created_cdb974_idx'), models.Index(fields=['uploaded_by'], name='admin_bulk__uploade_f46f6c_idx'), models.Index(fields=['branch'], name='admin_bulk__branch__521b40_idx')],
            },
        ),
    ]
