# Generated by Django 4.2.7 on 2026-03-25 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0014_remove_transaction_plans_txn_type_created_desc'),
        ('branches', '0001_initial'),
        ('admin_auth', '0002_adminuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_staff_payment_receipt_seq',
            },
        ),
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('customer_matri', models.CharField(db_index=True, max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('gpay_upi', 'GPay/UPI')], max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_payment_entries', to='branches.branch')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_payment_entries', to='plans.plan')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payment_entries', to='admin_auth.adminuser')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to='admin_auth.adminuser')),
            ],
            options={
                'db_table': 'admin_staff_payment_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['staff', '-created_at'], name='admin_staff_staff_i_4730ea_idx'), models.Index(fields=['branch', '-created_at'], name='admin_staff_branch__d9b1fa_idx')],
            },
        ),
    ]
