# Generated by Django 4.2.7 on 2026-03-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_remove_transaction_plans_txn_type_created_desc'),
        ('staff_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_payment_entry', to='plans.transaction'),
        ),
    ]
