# Generated by Django 4.2.7 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_payments", "0002_paymententry_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymententry",
            name="cashier_receipt_no",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="paymententry",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymententry",
            name="physical_receipt_no",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
