# Generated by Django 4.2.7 on 2026-03-23 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_auth', '0001_initial'),
        ('plans', '0013_transaction_type_created_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reviews', to='admin_auth.adminuser')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_review', to='plans.transaction')),
            ],
            options={
                'db_table': 'admin_payment_review',
                'ordering': ['-created_at'],
            },
        ),
    ]
