name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /opt/aiswaryamatrimonials/Matrimony_Backend

            git fetch origin
            git reset --hard origin/master

            docker compose down
            docker compose up -d --build

            docker compose exec -T django python manage.py migrate

            docker compose exec -T django python manage.py collectstatic --noinput

            docker image prune -f

            docker compose ps
